# Generated by Django 5.2.4 on 2025-07-29 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='count_listener',
            field=models.IntegerField(default=1, verbose_name='Кл-во слушателей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка песни'),
        ),
        migrations.AddField(
            model_name='song',
            name='text',
            field=models.TextField(default='текст', verbose_name='Текст песни'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='time_of_music',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время музыки'),
            preserve_default=False,
        ),
    ]
