# Generated by Django 4.2.21 on 2025-06-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Название')),
                ('color', models.CharField(max_length=300, null=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_begin', models.CharField(max_length=255, null=True, verbose_name='Начало выпуска от')),
                ('year_end', models.CharField(max_length=255, null=True, verbose_name='Год выпуска до')),
                ('seria', models.CharField(max_length=255, verbose_name='Серия')),
                ('img', models.ImageField(blank=True, null=True, upload_to='car/generation/', verbose_name='Фото поколение')),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название марки')),
                ('img', models.ImageField(blank=True, null=True, upload_to='car/mark/', verbose_name='Фото автомобиля')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная марка')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная модель')),
                ('id_car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_mark', to='cars.carmark')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип кузова')),
                ('img', models.ImageField(blank=True, null=True, upload_to='car/car_type/', verbose_name='Фото типа машины')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип сделки')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GearBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип Автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1900, verbose_name='Год выпуска')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объем двигателя (л)')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('distance_unit', models.CharField(choices=[('KM', 'Км'), ('MILE', 'Миля')], default='KM', max_length=10, verbose_name='Измерения расстояния')),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('SOM', 'Сом'), ('USD', 'Доллар')], default='Сом', max_length=10, verbose_name='Валюта цены')),
                ('vin_code', models.CharField(default='01KG000ABC', max_length=10, verbose_name='VIN код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('ctc_phone_1', models.CharField(default='+996', max_length=50, verbose_name='Телефонный номер для контакта1')),
                ('ctc_phone_2', models.CharField(default='+996', max_length=50, verbose_name='Телефонный номер для контакта2')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.availability', verbose_name='Наличии')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmark', verbose_name='Марка')),
                ('car_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cargeneration', verbose_name='Поколение')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Модель')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Тип кузова')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcolor', verbose_name='Цвет')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.condition', verbose_name='Техническое состояние')),
                ('count_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carowner', verbose_name='К-лво Владелец')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.custom', verbose_name='Техническое состояние')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.dealtype')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fuel', verbose_name='Тип двигателя')),
                ('gearbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.gearbox', verbose_name='Коробка передач')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.region', verbose_name='Регион продажи')),
                ('steering_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.steeringwheel', verbose_name='Руль')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Привод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicletype', verbose_name='Тип автомобиля')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carpost', verbose_name='Картинки автомобиля')),
            ],
            options={
                'verbose_name': 'Картинки автомобиля',
                'verbose_name_plural': 'Картинки автомобиля',
            },
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='id_car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
