# Generated by Django 5.2.1 on 2025-05-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название марки')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип машины')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('id_car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_mark', to='cars.carmark')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_begin', models.CharField(max_length=255, null=True, verbose_name='Начало выпуска от')),
                ('year_end', models.CharField(max_length=255, null=True, verbose_name='Год выпуска до')),
                ('seria', models.CharField(max_length=255, verbose_name='Серия')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото поколение')),
                ('id_car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype'),
        ),
    ]
