# Generated by Django 5.2.1 on 2025-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_availability_carcolors_carowner_condition_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmark',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная марка'),
        ),
        migrations.AlterField(
            model_name='carmark',
            name='img',
            field=models.ImageField(upload_to='car/mark/', verbose_name='Фото автомобиля'),
        ),
    ]
