# Generated by Django 5.2.1 on 2025-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmark_is_popular_alter_carmark_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная модель'),
        ),
    ]
