# Generated by Django 5.2.1 on 2025-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargeneration',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='car/generation/', verbose_name='Фото поколение'),
        ),
        migrations.AlterField(
            model_name='carmark',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='car/mark/', verbose_name='Фото автомобиля'),
        ),
    ]
