# Generated by Django 5.2.1 on 2025-05-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cargeneration_img_alter_carmark_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='car/car_type/', verbose_name='Фото типа машины'),
        ),
    ]
