# Generated by Django 5.2.1 on 2025-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cartype_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
