# Generated by Django 5.2.1 on 2025-05-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Картинки автомобиля',
                'verbose_name_plural': 'Картинки автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1900, verbose_name='Год выпуска')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объем двигателя (л)')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('distance_unit', models.CharField(choices=[('KM', 'Км'), ('MILE', 'Миля')], default='KM', verbose_name='Измерения расстояния')),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('SOM', 'Сом'), ('USD', 'Доллар')], default='Сом', verbose_name='Валюта цены')),
                ('vin_code', models.CharField(default='01KG000ABC', verbose_name='VIN код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('ctc_phone_1', models.CharField(default='+996', max_length=50, verbose_name='Телефонный номер для контакта1')),
                ('ctc_phone_2', models.CharField(default='+996', max_length=50, verbose_name='Телефонный номер для контакта2')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.availability', verbose_name='Наличии')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmark', verbose_name='Марка')),
                ('car_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cargeneration', verbose_name='Поколение')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип сделки')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип Автомобиля')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип кузова'),
        ),
        migrations.RenameModel(
            old_name='CarColors',
            new_name='CarColor',
        ),
        migrations.RenameModel(
            old_name='Customs',
            new_name='Custom',
        ),
        migrations.AddField(
            model_name='carpost',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.condition', verbose_name='Техническое состояние'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='count_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carowner', verbose_name='К-лво Владелец'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.custom', verbose_name='Техническое состояние'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fuel', verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.gearbox', verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.region', verbose_name='Регион продажи'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='steering_wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.steeringwheel', verbose_name='Руль'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carpost', verbose_name='Картинки автомобиля'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='deal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.dealtype'),
        ),
        migrations.AddField(
            model_name='carpost',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.vehicletype', verbose_name='Тип автомобиля'),
        ),
    ]
