# Generated by Django 4.2.21 on 2025-06-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='car/stories/', verbose_name='Оболожка истории')),
                ('link', models.URLField(blank=True, help_text='Если есть', max_length=500, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Историю',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StoriesImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание истории')),
                ('img', models.ImageField(upload_to='car/stories/many_img', verbose_name='Изображение истории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('stories_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.stories')),
            ],
        ),
    ]
