# Generated by Django 5.2.1 on 2025-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='img',
            field=models.ImageField(upload_to='car/stories/', verbose_name='Оболожка истории'),
        ),
        migrations.AlterField(
            model_name='storiesimg',
            name='img',
            field=models.ImageField(upload_to='car/stories/many_img', verbose_name='Изображение истории'),
        ),
    ]
