# Generated by Django 5.2.1 on 2025-05-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stories_img_alter_storiesimg_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Историю', 'verbose_name_plural': 'Истории'},
        ),
        migrations.RemoveField(
            model_name='stories',
            name='stories_img',
        ),
        migrations.AddField(
            model_name='storiesimg',
            name='stories_img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.storiesimg'),
            preserve_default=False,
        ),
    ]
